//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputSystem/PlayerChooseItems.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerChooseItems: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerChooseItems()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerChooseItems"",
    ""maps"": [
        {
            ""name"": ""Player"",
            ""id"": ""d9d6a4f9-e18f-47b3-95c2-e5181d282920"",
            ""actions"": [
                {
                    ""name"": ""EscapeChooseItem"",
                    ""type"": ""Button"",
                    ""id"": ""71d0129c-e763-47ff-987a-dae15bace942"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""ChooseItem"",
                    ""type"": ""Button"",
                    ""id"": ""dc26717d-d9fe-463a-8133-64128a319656"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""StartGame"",
                    ""type"": ""Button"",
                    ""id"": ""630f1c45-00f8-432e-96ff-284798014533"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""8d2c7fc1-081f-4177-a63e-f636e2b78d8d"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ChooseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4d36e046-a96d-45c8-bc51-b89e926a5cf6"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""EscapeChooseItem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f7dbbedf-ba57-4188-b3a1-182b360d79d1"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""StartGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Player
        m_Player = asset.FindActionMap("Player", throwIfNotFound: true);
        m_Player_EscapeChooseItem = m_Player.FindAction("EscapeChooseItem", throwIfNotFound: true);
        m_Player_ChooseItem = m_Player.FindAction("ChooseItem", throwIfNotFound: true);
        m_Player_StartGame = m_Player.FindAction("StartGame", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Player
    private readonly InputActionMap m_Player;
    private List<IPlayerActions> m_PlayerActionsCallbackInterfaces = new List<IPlayerActions>();
    private readonly InputAction m_Player_EscapeChooseItem;
    private readonly InputAction m_Player_ChooseItem;
    private readonly InputAction m_Player_StartGame;
    public struct PlayerActions
    {
        private @PlayerChooseItems m_Wrapper;
        public PlayerActions(@PlayerChooseItems wrapper) { m_Wrapper = wrapper; }
        public InputAction @EscapeChooseItem => m_Wrapper.m_Player_EscapeChooseItem;
        public InputAction @ChooseItem => m_Wrapper.m_Player_ChooseItem;
        public InputAction @StartGame => m_Wrapper.m_Player_StartGame;
        public InputActionMap Get() { return m_Wrapper.m_Player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void AddCallbacks(IPlayerActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Add(instance);
            @EscapeChooseItem.started += instance.OnEscapeChooseItem;
            @EscapeChooseItem.performed += instance.OnEscapeChooseItem;
            @EscapeChooseItem.canceled += instance.OnEscapeChooseItem;
            @ChooseItem.started += instance.OnChooseItem;
            @ChooseItem.performed += instance.OnChooseItem;
            @ChooseItem.canceled += instance.OnChooseItem;
            @StartGame.started += instance.OnStartGame;
            @StartGame.performed += instance.OnStartGame;
            @StartGame.canceled += instance.OnStartGame;
        }

        private void UnregisterCallbacks(IPlayerActions instance)
        {
            @EscapeChooseItem.started -= instance.OnEscapeChooseItem;
            @EscapeChooseItem.performed -= instance.OnEscapeChooseItem;
            @EscapeChooseItem.canceled -= instance.OnEscapeChooseItem;
            @ChooseItem.started -= instance.OnChooseItem;
            @ChooseItem.performed -= instance.OnChooseItem;
            @ChooseItem.canceled -= instance.OnChooseItem;
            @StartGame.started -= instance.OnStartGame;
            @StartGame.performed -= instance.OnStartGame;
            @StartGame.canceled -= instance.OnStartGame;
        }

        public void RemoveCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPlayerActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PlayerActions @Player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnEscapeChooseItem(InputAction.CallbackContext context);
        void OnChooseItem(InputAction.CallbackContext context);
        void OnStartGame(InputAction.CallbackContext context);
    }
}
